# Generated by Django 2.2.1 on 2019-06-28 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofileinfo_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='is_active',
        ),
    ]
